:page-layout: certification 
= TCK Results

As required by the https://www.eclipse.org/legal/tck.php[Eclipse Foundation Technology Compatibility Kit License], following is a summary of the TCK results for releases of Microprofile Metrics 3.0.

== Open Liberty 20.0.0.12 Microprofile Metrics 3.0 Certification Summary

* Product Name, Version and download URL (if applicable):
+
https://openliberty.io/download[Open Liberty]

* Specification Name, Version and download URL:
+
https://microprofile.io/project/eclipse/microprofile-metrics[Microprofile Metrics 3.0]

* Public URL of TCK Results Summary:
+
link:TCK-Results.html[TCK results summary]

* Java runtime used to run the implementation:
+
Java 8 and Java 11

* Summary of the information for the certification environment, operating system, cloud, ...:
+
Apache Derby, Linux, Ubuntu 16.04

Test results:

----
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.MetricFilterTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.353 sec - in org.eclipse.microprofile.metrics.tck.MetricFilterTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.MetricIDTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.478 sec - in org.eclipse.microprofile.metrics.tck.MetricIDTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.MetricRegistryTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.959 sec - in org.eclipse.microprofile.metrics.tck.MetricRegistryTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.cdi.ApplicationScopedTimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.923 sec - in org.eclipse.microprofile.metrics.tck.cdi.ApplicationScopedTimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.cdi.GaugeInjectionBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.944 sec - in org.eclipse.microprofile.metrics.tck.cdi.GaugeInjectionBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.cdi.MeterInjectionBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.93 sec - in org.eclipse.microprofile.metrics.tck.cdi.MeterInjectionBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.cdi.SimpleTimerInjectionBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.909 sec - in org.eclipse.microprofile.metrics.tck.cdi.SimpleTimerInjectionBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.cdi.TimerInjectionBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.032 sec - in org.eclipse.microprofile.metrics.tck.cdi.TimerInjectionBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.cdi.stereotype.StereotypeCountedClassBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.866 sec - in org.eclipse.microprofile.metrics.tck.cdi.stereotype.StereotypeCountedClassBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.inheritance.InheritedGaugeMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.995 sec - in org.eclipse.microprofile.metrics.tck.inheritance.InheritedGaugeMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.inheritance.InheritedSimplyTimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.884 sec - in org.eclipse.microprofile.metrics.tck.inheritance.InheritedSimplyTimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.inheritance.InheritedTimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.341 sec - in org.eclipse.microprofile.metrics.tck.inheritance.InheritedTimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.inheritance.VisibilitySimplyTimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.916 sec - in org.eclipse.microprofile.metrics.tck.inheritance.VisibilitySimplyTimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.inheritance.VisibilityTimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.88 sec - in org.eclipse.microprofile.metrics.tck.inheritance.VisibilityTimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.ConcreteExtendedTimedBeanTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.392 sec - in org.eclipse.microprofile.metrics.tck.metrics.ConcreteExtendedTimedBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.ConcreteTimedBeanTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.872 sec - in org.eclipse.microprofile.metrics.tck.metrics.ConcreteTimedBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugeFunctionalTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 95.448 sec - in org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugeFunctionalTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugeTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.981 sec - in org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugeTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedClassBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.934 sec - in org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedClassBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedConstructorBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.904 sec - in org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedConstructorBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.889 sec - in org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.CountedClassBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.904 sec - in org.eclipse.microprofile.metrics.tck.metrics.CountedClassBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.CountedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.95 sec - in org.eclipse.microprofile.metrics.tck.metrics.CountedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.CountedMethodTagBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.96 sec - in org.eclipse.microprofile.metrics.tck.metrics.CountedMethodTagBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.CounterFieldBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.875 sec - in org.eclipse.microprofile.metrics.tck.metrics.CounterFieldBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.CounterTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.408 sec - in org.eclipse.microprofile.metrics.tck.metrics.CounterTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.DefaultNameMetricMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.377 sec - in org.eclipse.microprofile.metrics.tck.metrics.DefaultNameMetricMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.GaugeMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.509 sec - in org.eclipse.microprofile.metrics.tck.metrics.GaugeMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.GaugeTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.393 sec - in org.eclipse.microprofile.metrics.tck.metrics.GaugeTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.HistogramFieldBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.431 sec - in org.eclipse.microprofile.metrics.tck.metrics.HistogramFieldBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.HistogramTest
-------------------------------------------------------------------------------
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.966 sec - in org.eclipse.microprofile.metrics.tck.metrics.HistogramTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.MeteredClassBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.42 sec - in org.eclipse.microprofile.metrics.tck.metrics.MeteredClassBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.MeteredConstructorBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.217 sec - in org.eclipse.microprofile.metrics.tck.metrics.MeteredConstructorBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.MeteredMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.407 sec - in org.eclipse.microprofile.metrics.tck.metrics.MeteredMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.MultipleMetricsConstructorBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.969 sec - in org.eclipse.microprofile.metrics.tck.metrics.MultipleMetricsConstructorBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.MultipleMetricsMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.884 sec - in org.eclipse.microprofile.metrics.tck.metrics.MultipleMetricsMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.OverloadedTimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.025 sec - in org.eclipse.microprofile.metrics.tck.metrics.OverloadedTimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.SimpleTimerFieldBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.999 sec - in org.eclipse.microprofile.metrics.tck.metrics.SimpleTimerFieldBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.SimpleTimerFunctionalTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 95.927 sec - in org.eclipse.microprofile.metrics.tck.metrics.SimpleTimerFunctionalTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.SimpleTimerTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.856 sec - in org.eclipse.microprofile.metrics.tck.metrics.SimpleTimerTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedClassBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.986 sec - in org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedClassBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedConstructorBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.944 sec - in org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedConstructorBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedMethodBeanLookupTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.885 sec - in org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedMethodBeanLookupTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.435 sec - in org.eclipse.microprofile.metrics.tck.metrics.SimplyTimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.TimedClassBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.955 sec - in org.eclipse.microprofile.metrics.tck.metrics.TimedClassBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.TimedConstructorBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.86 sec - in org.eclipse.microprofile.metrics.tck.metrics.TimedConstructorBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.TimedMethodBeanLookupTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.418 sec - in org.eclipse.microprofile.metrics.tck.metrics.TimedMethodBeanLookupTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.TimedMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.852 sec - in org.eclipse.microprofile.metrics.tck.metrics.TimedMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.metrics.TimerFieldBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.97 sec - in org.eclipse.microprofile.metrics.tck.metrics.TimerFieldBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.CounterFieldTagBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.39 sec - in org.eclipse.microprofile.metrics.tck.tags.CounterFieldTagBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.GaugeTagMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.539 sec - in org.eclipse.microprofile.metrics.tck.tags.GaugeTagMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.HistogramTagFieldBeanTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.024 sec - in org.eclipse.microprofile.metrics.tck.tags.HistogramTagFieldBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.MeteredTagMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.478 sec - in org.eclipse.microprofile.metrics.tck.tags.MeteredTagMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.SimplerTimerTagFieldBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.872 sec - in org.eclipse.microprofile.metrics.tck.tags.SimplerTimerTagFieldBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.SimplyTimedTagMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.373 sec - in org.eclipse.microprofile.metrics.tck.tags.SimplyTimedTagMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.TagsTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.891 sec - in org.eclipse.microprofile.metrics.tck.tags.TagsTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.TimedTagMethodBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.418 sec - in org.eclipse.microprofile.metrics.tck.tags.TimedTagMethodBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.tck.tags.TimerTagFieldBeanTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.404 sec - in org.eclipse.microprofile.metrics.tck.tags.TimerTagFieldBeanTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.test.MpMetricTest
-------------------------------------------------------------------------------
Tests run: 47, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.465 sec - in org.eclipse.microprofile.metrics.test.MpMetricTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.test.ReusedMetricsTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.938 sec - in org.eclipse.microprofile.metrics.test.ReusedMetricsTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.test.multipleinstances.MultipleBeanInstancesTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.791 sec - in org.eclipse.microprofile.metrics.test.multipleinstances.MultipleBeanInstancesTest
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.metrics.test.optional.MpMetricOptionalTest
-------------------------------------------------------------------------------
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.244 sec - in org.eclipse.microprofile.metrics.test.optional.MpMetricOptionalTest

Results :

Tests run: 214, Failures: 0, Errors: 0, Skipped: 0

----
