:page-layout: certification
:page-spec: JAKARTAEE
:page-version: 11
= TCK Results

As required by the https://www.eclipse.org/legal/tck.php[Eclipse Foundation Technology Compatibility Kit License], the following is a summary of the TCK results for Jakarta EE Core Profile 11.

== Open Liberty 26.0.0.5 Jakarta EE Core Profile 11 using Java 17 Certification Summary

* Product Name, Version and download URL (if applicable):
+
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/26.0.0.5/openliberty-webProfile11-26.0.0.5.zip[Open Liberty 26.0.0.5]

* Specification Name, Version and download URL:
+
https://jakarta.ee/specifications/coreprofile/11[Jakarta EE Core Profile 11]

* TCK Version, digital SHA-256 fingerprint and download URL:
+
https://download.eclipse.org/jakartaee/coreprofile/11.0/jakarta-core-profile-tck-11.0.0.zip[Jakarta EE Core Profile TCK 11.0.0],
SHA-256: `0357bfab7025972edb2bf50277b6b4206b499a2961bc94e783f34782cc4a9bda`

* Public URL of TCK Results Summary:
+
link:26.0.0.5-Java17-TCKResults.html[TCK results summary]

* Any Additional Specification Certification Requirements:
+
Jakarta Annotations
https://download.eclipse.org/jakartaee/annotations/3.0/jakarta-annotations-tck-3.0.0.zip[jakarta-annotations-tck-3.0.0.zip],
SHA-256: `9421c6ca66274d32dfb408848f75a42d57f120599fe0d8403c5c5c1141d5ac4d`
+
Jakarta Contexts and Dependency Injection
https://download.eclipse.org/jakartaee/cdi/4.1/cdi-tck-4.1.0-dist.zip[cdi-tck-4.1.0-dist.zip],
SHA-256: `446029ee1ce694d2a9ae8893d16be7afd7e1c0ed8705064b7095af174cf97ea0`
+
Jakarta Dependency Injection
https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip[jakarta.inject-tck-2.0.2-bin.zip],
SHA-256: `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972`
+
Jakarta JSON Binding
https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip[jakarta-jsonb-tck-3.0.0.zip],
SHA-256: `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`
+
Jakarta JSON Processing
https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.1.zip[jakarta-jsonp-tck-2.1.1.zip],
SHA-256: `949f203de84deffa8c7892b555918e42f1dd220ccb7b6800741ea58af62737c1`
+
Jakarta RESTful Web Services
https://download.eclipse.org/jakartaee/restful-ws/4.0/jakarta-restful-ws-tck-4.0.1.zip[jakarta-restful-ws-tck-4.0.1.zip],
SHA-256: `b6290c1b5b3d2fdd9cc700a999243492a7e27b94a9b6af1974ff4dc5bfbf98f2`
+
* Java runtime used to run the implementation:
----
java version "17.0.13"
IBM Semeru Runtime Certified Edition (17.0.13+11)
----

* Summary of the information for the certification environment, operating system, cloud, ...:
+
Apache Derby 10.16.1.1, Linux, Ubuntu 18

*Test results:*

----


cdi-langmodel
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

Jakarta Annotations
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0


Jakarta Contexts and Dependency Injection
Tests run: 779, Failures: 0, Errors: 0, Skipped: 0


Jakarta Core Profile
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0


Jakarta Dependency Injection
Tests run: 50, Failures: 0, Errors: 0, Skipped: 0


Jakarta JSON Binding
Tests run: 295, Failures: 0, Errors: 0, Skipped: 5


Jakarta JSON Processing
Tests run: 197, Failures: 0, Errors: 0, Skipped: 0


Jakarta RESTful Web Services
Tests run: 2655, Failures: 0, Errors: 0, Skipped: 128

----
